const queries = [
  {
    "input name": "Acorn Law P.C.",
    "input phone": "",
    "input website": "https://https//acornlawpc.com/",
    input_facebook: "https://www.facebook.com/acornfurnitureworkshops",
  },
  {
    "input name": "Advance Net Support",
    "input phone": "(786) 426-3492",
    "input website": "",
    input_facebook: "",
  },
  {
    "input name": "Aroostook",
    "input phone": "207.762.9321",
    "input website": "",
    input_facebook: "",
  },
  {
    "input name": "&AWL",
    "input phone": "",
    "input website": "awlsnap.com",
    input_facebook: "",
  },
  {
    "input name": "RyanLBatesDDS",
    "input phone": "(509) 276-6996",
    "input website": "google.com",
    input_facebook: "",
  },
  {
    "input name": "Cadott Family Restaurant Limited",
    "input phone": "715.978.0027",
    "input website": "google.com",
    input_facebook: "",
  },
  {
    "input name": "Denham's Florist Inc",
    "input phone": "(706) 685.0182",
    "input website": "http://dreamservicesoftware.com",
    input_facebook: "",
  },
  {
    "input name": "Garrett-Wietholter-State-Farm-Agent",
    "input phone": "(317) 873-3230",
    "input website": "google.com",
    input_facebook: "",
  },
  {
    "input name": "GSS",
    "input phone": "",
    "input website": "",
    input_facebook: "https://www.facebook.com/GSSstrings/",
  },
  {
    "input name": "Hueboost Services //",
    "input phone": "(+877) 449-5079",
    "input website": "",
    input_facebook: "",
  },
  {
    "input name": "American Inns of Court Company",
    "input phone": "+1703-684-3590",
    "input website": "innsc.com",
    input_facebook: "",
  },
  {
    "input name": "JETT Business Technology LTD",
    "input phone": "(678) 387-5715",
    "input website": "https://www.google.com/",
    input_facebook: "",
  },
  {
    "input name": "NCCA Inc.",
    "input phone": "207.762.9321",
    "input website": "",
    input_facebook: "https://www.facebook.com/musselrockcloggers/",
  },
  {
    "input name": "NY AL Elevator",
    "input phone": "",
    "input website": "elevator.io",
    input_facebook: "",
  },
  {
    "input name": "NY Staffing LLC.",
    "input phone": "",
    "input website": "nyexecstaffing.com",
    input_facebook: "",
  },
  {
    "input name": "Puppet Heap USA",
    "input phone": "",
    "input website": "puppet.io",
    input_facebook: "https://facebook.com/puppetheap",
  },
  {
    "input name": "SafetyChain Software Services Pty. Ltd.",
    "input phone": "",
    "input website": "https://safetychain.com/about-us",
    input_facebook: "",
  },
  {
    "input name": "SBS*",
    "input phone": "",
    "input website": "http://sbstransportllc.com/index.html?lang=en",
    input_facebook:
      "https://www.facebook.com/SBS-Transport-LLC-101932885163238",
  },
  {
    "input name": "SteppIR Tree Services",
    "input phone": "",
    "input website": "steppir.com",
    input_facebook: "https://www.facebook.com/SteppIR/",
  },
  {
    "input name": "Templo Ebenezer Weslaco Holding",
    "input phone": "(956) 968-8142",
    "input website": "",
    input_facebook: "",
  },
  {
    "input name": "The Greenwich Cincinnati",
    "input phone": "+1513-221-1151",
    "input website": "",
    input_facebook: "",
  },
  {
    "input name": "Inc. Mercury",
    "input phone": "",
    "input website": "",
    input_facebook: "https://facebook.com/bluemercury",
  },
  {
    "input name": "Total Seal Inc.",
    "input phone": "",
    "input website": "",
    input_facebook: "https://www.facebook.com/totalseal.pistonrings/",
  },
  {
    "input name": "True Audio Services",
    "input phone": "865-494-3388",
    "input website": "trueaudio.com",
    input_facebook: "",
  },
  {
    "input name": "ViruStar LLC.",
    "input phone": "",
    "input website": "viru.com",
    input_facebook: "",
  },
  {
    "input name": "W. Works Holding(s)",
    "input phone": "",
    "input website": "wworks.net",
    input_facebook: "",
  },
  {
    "input name": "Forge Marketing & Management Pty.",
    "input phone": "",
    "input website": "",
    input_facebook: "https://www.facebook.com/workitstudio/",
  },
  {
    "input name": "A W Brueggemann Co.",
    "input phone": "",
    "input website": "awbrueggemann.com",
    input_facebook: "",
  },
  {
    "input name": "Blue Ridge Chair - Limited",
    "input phone": "",
    "input website": "https://www.blueridgechair.com",
    input_facebook: "",
  },
  {
    "input name": "Cedar Work Inc.",
    "input phone": "",
    "input website": "cedarwork.org",
    input_facebook: "",
  },
  {
    "input name": "Inc.",
    "input phone": "",
    "input website": "",
    input_facebook: "https://facebook.com/bluemercury",
  },
  {
    "input name": "..",
    "input phone": "",
    "input website": "steppir.com",
    input_facebook: "",
  },
];
export default queries;
